services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name : "node-app"
    ports:
      - "3000:3000"
    networks:
      - app
    restart: always  
networks:
  app:
    driver: bridge
