services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name : "node-app"
    ports:
      - "3000:3000"
    network_mode : "app"
    deploy:
      restart_policy:
        condition: on-failure
